### PR TITLE
Initial search bar

### PR DESCRIPTION
**Pull request by GroovinChip**
- Minor refactoring
- Initial searchbar

### CODE REVIEW

**Comment by GroovinChip** [comment]
Closes #1

**Comment by ThinkDigitalSoftware** [comment]
I'd prefer this to keep the header but have search there too. I want to adhere to the colors of the site. It looks too light now, to me

**Comment by GroovinChip** [comment]
Wouldn't it look odd to have the appBar and the search underneath it?

**Comment by ThinkDigitalSoftware** [comment]
I know it's web, but it doesn't look that bad. I'm open for other options, but I definitely want to keep with the theme so that it looks official
Screenshot_20190609-174648_Chrome

**Comment by ThinkDigitalSoftware** [comment]
Can we make the app bar a sliver that can disappear and the search be pinned?

**Comment by GroovinChip** [comment]
Actually that's not a bad idea. I'll look into it.

**Comment by GroovinChip** [comment]
Updated UI for sliver scrolling and pub logo @ThinkDigitalRepair

**Review by ThinkDigitalSoftware — COMMENTED** [review]
Thanks, I'll take a look at this shortly

**Pull request closed without merging**
