### PR TITLE
Major UI Update

### PR DESCRIPTION
**Pull request by GroovinChip**
- Matches the look of the website by including a segmented control, a dark background behind the search bar and segmented control, and a dark search bar
- Introduces a menu button to launch a bottom sheet that will contain a theme toggle and app information (like version, authors) in the future
- Includes code to retrieve pages of packages, commented out and replaced with mock data due to API issues

Screenshot:

image

### CODE REVIEW

**Comment by ThinkDigitalSoftware** [comment]
Ooh, the bottom sheet will include things that are in the sidebar on the website?

**Comment by GroovinChip** [comment]
Oh, if you want stuff from the sidebar then we should have a side drawer, there's too much there for a sheet

**Comment by ThinkDigitalSoftware** [comment]
Merged

**Comment by GroovinChip** [comment]
Noice

**Pull request closed without merging**
