### PR TITLE
update favorite icon

### PR DESCRIPTION
**Pull request by GroovinChip**
Changed icon used to favorite a package from a star to a heart

### CODE REVIEW

**Comment by ThinkDigitalSoftware** [comment]
This is good. It's such a small PR though :)

**Comment by GroovinChip** [comment]
Lol just trying to keep things simple

**Comment by GroovinChip** [comment]
Lol just trying to keep things simple

**Comment by ThinkDigitalSoftware** [comment]
Lol. Appreciate that. But it ends up being the same thing, lol. If you're the only one committing to a branch, no rebase will be necessary and the complication won't be an issue. If I commit to it too, you'll need to rebase before you do a PR and then it'll be easy

**Pull request merged**
